name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm run prettier:check --if-present
      #- run: npm test
      - name: Build Package
        run: npm run build --if-present
      - name: Publish Package
        run: npm publish --access public --if-present
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
